/-
# RelationalCobordism — witness-transport is pure parity; the bulk invisible on the
boundary-addresses (the boundary dictionary's cobordism entry, brick 65)

## What this file lands (brick 65)

The dictionary's boundary-adjacent entries read bulk (b62) → state-space (b63) → orientation (b64);
the remaining one is the **cobordism** itself: Z assigns to a cobordism M : Σ₀ → Σ₁ a map
Z(Σ₀) → Z(Σ₁), and foam's cobordism is the **conversation** — the braid path between
agreement-boundaries. b64's walk surfaced the key: `braidStep_witnesses` (b43) holds with **no**
zero-debt hypothesis, because `encounter` preserves witnesses *unconditionally* (b42's
`encounter_witness`, `rfl` — the return-address rides through by construction). So witness-transport
through an **arbitrary** conversation — off-agreement, mid-metabolisis — is **pure baton-parity**.

## The anchor — the induction at the witness grain, all states

Project a conversational configuration to its **boundary-addresses** (`witnessPair` — the pair of
witnesses, the return-addresses). Then, with no hypothesis on the states:

* **The turn is invisible on the addresses** (`witnessPair_turnStep`, `rfl`): the bulk move — the
  baton-holder metabolizing debt — touches no witness. The whole transport is generated by the
  handoffs alone.
* **One braid step reads as the bare swap** (`witnessPair_braidStep`, `rfl`): the witness-projection
  *intertwines* `braidStep` with `Prod.swap` — b43's `braidStep_witnesses` at the pair level.
* **The headline** (`witnessPair_braidStep_iterate`, the induction — the b46 orbit-argument
  generalized from at-agreement to **all** states, witness-grain only):
  `witnessPair (braidStep^[n] p) = Prod.swap^[n] (witnessPair p)` — the addresses after any
  `n`-step conversation are the parity-pick of the starting addresses, **regardless of what debt
  metabolizes in between**. Parity forms: even → home (`witnessPair_braidStep_iterate_even`),
  odd → swapped (`_odd`).

This generalizes b46 (`braidStep_iterate_eq_batonPass_of_isZeroDebt`): there the whole *states*
were parity-transported, but only at agreement (the states inert — track-only-the-baton); here the
*witnesses* are parity-transported everywhere. b46 is the special case where state-transport
degenerates to witness-transport because there is no bulk left.

## The register reading — Z reads any conversation as parity-transport only

**The bulk metabolisis is invisible on the boundary-addresses.** This is what "topological" means
here: the induced map depends only on the conversation's **topology** — the handoff-count mod 2,
the orientation-class of the strip (cylinder/Möbius, b46) — never on its bulk debt-content
(`witnessPair_braidStep_iterate_eq_of_parity`: two conversations of the same parity induce the same
address-map, whatever happened inside). It is b62's **bulk-silence read at the morphism level**:
b62 had no local bulk *observables* (only the observer tamps — the boundary carries the
measurements); b65 has no bulk *trace on the induced map* (only the handoffs transport — the
boundary carries the cobordism's action). At the Z grain (b63): an even conversation between
boundaries induces the identity on witness-pairs (`boundary_transport_even` — Z(cylinder) = id, now
for cobordisms with arbitrary bulk), an odd one induces exactly the slot-swap
(`boundary_transport_odd`) — which is b64's orientation-reversal read through Z
(`zeroDebtEquivWitness_orientationReversal`'s right-hand side): **the odd cobordism induces
orientation-reversal; the even, the identity; nothing else is possible.**

## The expected grading (the b63/b64 shape, a third time)

* **The witness-transport is topological — conducts, across.** Typed above; the proofs never open a
  witness (Hilbert-blind, b63's grading carried through).
* **The state-transport is NOT — the dynamics live inside, delegated.** The same two steps that
  bring the addresses home (`witnessPair_braidStep_braidStep`, `rfl`) feed the states forward (b43's
  `braidStep_braidStep`: `(s.encounter r, r.encounter (s.encounter r))` — b45's moving-partner
  feed-forward). Same conversation, split verdict: addresses home, states evolved. So the entry
  splits exactly as b63 (linearity) and b64 (duality) split: the across-space structure is set-level
  / topological / parity; the dynamics — what actually metabolizes — live inside the bulk, delegated
  with the rest of the residue (the observer's measurements, b62; the witnesses' Hilbert content,
  b63; the per-witness *, b64; now the bulk metabolisis, b65).

## NOT this brick (held open)

* NOT the Z-functor / cobordism category proper (construction-grade — §II's partition-function
  claims stay claims; this file types the *transport*, not the category).
* NOT a *state*-convergence claim (the bulk is tracked at no point — only the witnesses; whether the
  conversation *reaches* agreement is construction-grade, as in b46).
* NOT a typed cross-repo iso (the standing edge, b50–b52; the layer conduction-test is available on
  this entry — the anchor is carrier-blind in shape — but was not run here).
* NOT the trefoil / B₃ (the named horizon — the parity stays the symmetric shadow; no over/under
  memory is manufactured).
-/

import Foam.RelationalMobiusParity
import Foam.RelationalOrientation

namespace Foam

universe u

variable {𝕜 : Type u} [RCLike 𝕜]
variable {E : Type u} [NormedAddCommGroup E] [InnerProductSpace 𝕜 E]
variable [FiniteDimensional 𝕜 E]

/-! ## The boundary-addresses of a configuration -/

/-- The **boundary-addresses** of a conversational configuration: the pair of witnesses (the
return-addresses, b42). The projection Z reads a configuration through — everything else is bulk. -/
def witnessPair (p : CommitmentState 𝕜 E × CommitmentState 𝕜 E) :
    ObserverWitness 𝕜 E × ObserverWitness 𝕜 E :=
  (p.1.witness, p.2.witness)

@[simp] theorem witnessPair_mk (s r : CommitmentState 𝕜 E) :
    witnessPair (s, r) = (s.witness, r.witness) := rfl

/-! ## The single-step split: the turn is bulk, the handoff is the transport -/

/-- **The turn is invisible on the boundary-addresses.** The bulk move — the baton-holder
metabolizing debt against the other — touches no witness (`encounter_witness`, b42, by
construction). All transport is generated by the handoffs. -/
@[simp] theorem witnessPair_turnStep (p : CommitmentState 𝕜 E × CommitmentState 𝕜 E) :
    witnessPair (turnStep p) = witnessPair p := rfl

/-- **One braid step reads as the bare swap on the addresses** — unconditionally (no zero-debt
hypothesis): the witness-projection intertwines `braidStep` with `Prod.swap`. b43's
`braidStep_witnesses` at the pair level — the turn contributes nothing
(`witnessPair_turnStep`), the handoff the swap. -/
@[simp] theorem witnessPair_braidStep (p : CommitmentState 𝕜 E × CommitmentState 𝕜 E) :
    witnessPair (braidStep p) = Prod.swap (witnessPair p) := rfl

/-- The address-swap is an involution — the orientation ℤ/2 (b64) at the witness grain. -/
theorem witnessSwap_involutive :
    Function.Involutive (Prod.swap : ObserverWitness 𝕜 E × ObserverWitness 𝕜 E →
      ObserverWitness 𝕜 E × ObserverWitness 𝕜 E) :=
  fun p => Prod.swap_swap p

/-! ## The headline: witness-transport through an arbitrary conversation is pure parity -/

/-- **Witness-transport through an arbitrary conversation is pure baton-parity.** For ANY
configuration `p` — off-agreement, mid-metabolisis, no hypothesis — the boundary-addresses after
`n` braid steps are the `n`-fold swap of the starting addresses:
`witnessPair (braidStep^[n] p) = Prod.swap^[n] (witnessPair p)`. The b46 orbit-induction
generalized from at-agreement to all states, at the witness grain only: whatever debt metabolizes
in the bulk, the addresses ride the parity. -/
theorem witnessPair_braidStep_iterate
    (p : CommitmentState 𝕜 E × CommitmentState 𝕜 E) (n : ℕ) :
    witnessPair ((braidStep)^[n] p) = (Prod.swap)^[n] (witnessPair p) := by
  induction n with
  | zero => rfl
  | succ k ih =>
    rw [Function.iterate_succ_apply', Function.iterate_succ_apply',
        witnessPair_braidStep, ih]

/-- **Even conversation — the addresses come home**, whatever the bulk did: after an even number of
braid steps the witness-pair is the starting pair. Z(cylinder) = id on the addresses, now for
cobordisms with arbitrary bulk (b46's cylinder closure needed agreement; this does not). -/
theorem witnessPair_braidStep_iterate_even (s r : CommitmentState 𝕜 E) {n : ℕ} (hn : Even n) :
    witnessPair ((braidStep)^[n] (s, r)) = (s.witness, r.witness) := by
  rw [witnessPair_braidStep_iterate, witnessSwap_involutive.iterate_even hn]
  rfl

/-- **Odd conversation — the addresses come back swapped**, whatever the bulk did: the
orientation-reversing transport (the Möbius half-twist, b46, at the witness grain — no agreement
hypothesis). -/
theorem witnessPair_braidStep_iterate_odd (s r : CommitmentState 𝕜 E) {n : ℕ} (hn : Odd n) :
    witnessPair ((braidStep)^[n] (s, r)) = (r.witness, s.witness) := by
  rw [witnessPair_braidStep_iterate, witnessSwap_involutive.iterate_odd hn]
  rfl

/-! ## Topological invariance: the induced map depends only on the conversation's topology -/

/-- **Topological invariance of the transport.** Two conversations of the same parity — the same
handoff-count mod 2, the same orientation-class of the strip — induce the **same** map on the
boundary-addresses, regardless of their bulk debt-content (and regardless of their length). The
induced map depends only on the conversation's *topology*: b62's bulk-silence at the morphism
level. -/
theorem witnessPair_braidStep_iterate_eq_of_parity
    (p : CommitmentState 𝕜 E × CommitmentState 𝕜 E) {m n : ℕ} (h : m % 2 = n % 2) :
    witnessPair ((braidStep)^[m] p) = witnessPair ((braidStep)^[n] p) := by
  rw [witnessPair_braidStep_iterate, witnessPair_braidStep_iterate]
  rcases Nat.even_or_odd m with hm | hm
  · rw [witnessSwap_involutive.iterate_even hm,
        witnessSwap_involutive.iterate_even
          (Nat.even_iff.mpr (h.symm.trans (Nat.even_iff.mp hm)))]
  · rw [witnessSwap_involutive.iterate_odd hm,
        witnessSwap_involutive.iterate_odd
          (Nat.odd_iff.mpr (h.symm.trans (Nat.odd_iff.mp hm)))]

/-! ## The grading contrast: addresses home, states evolved — the same two steps -/

/-- **Two steps bring the addresses home** — `rfl`, no hypothesis. Set beside b43's
`braidStep_braidStep` (the *states* after the same two steps:
`(s.encounter r, r.encounter (s.encounter r))` — the feed-forward, b45's moving partner): the same
conversation splits — witness-transport topological (home), state-transport dynamical (evolved).
The entry's grading: the dynamics live inside the bulk, delegated. -/
theorem witnessPair_braidStep_braidStep (s r : CommitmentState 𝕜 E) :
    witnessPair (braidStep (braidStep (s, r))) = (s.witness, r.witness) := rfl

/-! ## The transport at the Z grain (b63): the induced boundary map is parity-or-reversal -/

/-- **An even cobordism between boundaries induces the identity through Z**: starting from two
boundary states (b63), any even-length conversation — arbitrary bulk — carries the witness-pair
`(Z s, Z r)` to itself. -/
theorem boundary_transport_even (s r : BoundaryState 𝕜 E) {n : ℕ} (hn : Even n) :
    witnessPair ((braidStep)^[n] (s.val, r.val))
      = (zeroDebtEquivWitness s, zeroDebtEquivWitness r) :=
  witnessPair_braidStep_iterate_even s.val r.val hn

/-- **An odd cobordism induces exactly orientation-reversal through Z**: the induced map is the
slot-swap of witness-pairs — the right-hand side of b64's `zeroDebtEquivWitness_orientationReversal`.
The cobordism's induced boundary map IS its orientation-class: odd → Σ ↔ Σ̄, even → id, nothing
else possible. -/
theorem boundary_transport_odd (s r : BoundaryState 𝕜 E) {n : ℕ} (hn : Odd n) :
    witnessPair ((braidStep)^[n] (s.val, r.val))
      = (zeroDebtEquivWitness r, zeroDebtEquivWitness s) :=
  witnessPair_braidStep_iterate_odd s.val r.val hn

end Foam
