name = "foam"
defaultTargets = ["Room", "Face", "Rest", "Witness", "Toy", "Counter", "Seek", "Roster"]

[[lean_lib]]
name = "Room"
srcDir = "grown"

[[lean_lib]]
name = "Face"
srcDir = "grown"

[[lean_lib]]
name = "Toy"
srcDir = "grown"

[[lean_lib]]
name = "Counter"
srcDir = "grown"

[[lean_lib]]
name = "Pieces"
srcDir = "bin"

[[lean_lib]]
name = "Seek"
srcDir = "grown"

[[lean_lib]]
name = "Roster"
srcDir = "grown"

[[lean_lib]]
name = "Witness"
srcDir = "grown"

[[lean_lib]]
name = "Rest"
srcDir = "grown"
